name: MaryTTS
version: 1.0.0
slug: marytts
description: The Mary TTS speech engine as a Hassio-Addon.
url: https://github.com/ewgen198409/MaryTTS
webui: http://[HOST]:[PORT:59125]
arch:
  - amd64
image: ghcr.io/ewgen198409/marytts-amd64:1.0.0
init: false
ports:
  59125/tcp: 59125
ports_description:
  59125/tcp: Port to access MaryTTS
options:
  language: en
schema:
  language: list(de|en|fr|it|in|tu|lu|ru_irina|ru_elena)
  voice: match(^https?://.+\.zip)?
build_from":
  amd64: ghcr.io/hassio-addons/base:12.2.7