{
  "name": "MaryTTS",
  "version": "1.0.0",
  "slug": "marytts",
  "description": "TTS server based on MaryTTS",
  "startup": "services",
  "boot": "auto",
  "arch": ["amd64"],
  "ports": {
    "59125/tcp": 59125
  },
  "build_from": {
    "amd64": "openjdk:8-jdk"
  }
}