name: MaryTTS
version: 1.0.0
slug: marytts
description: The Mary TTS speech engine as a Hassio-Addon.
url: https://github.com/ewgen198409/MaryTTS
webui: http://[HOST]:[PORT:59125]
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: ghcr.io/ewgen198409/marytts-{arch}
init: false
ports:
  59125/tcp: 59125
ports_description:
  59125/tcp: Port to access MaryTTS
options:
  language: en
schema:
  language: list(de|en|fr|it|in|tu|lu|ru_irina|ru_elena)
  voice: match(^https?://.+\.zip)?
