name: Draft release from new main push

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  workflows:
    uses: ewgen198409/workflows/.github/workflows/release-drafter.yaml@main
    permissions:
      contents: write
      pull-requests: read
