name: PR title

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  workflows:
    uses: ewgen198409/workflows/.github/workflows/pr-title.yaml@main
    permissions:
      contents: read
      pull-requests: write
